library(lubridate)
library(data.table)
library(dplyr)
a=fread("ExData_Plotting1/household_power_consumption.txt",na.strings = c("?"))
a1=filter(a,dmy(Date)=="2007-02-01"|dmy(Date)=="2007-02-02")
setwd("ExData_Plotting1")
a2=dmy(a1$Date)+hms(a1$Time)
png(file="plot2.png",width =480,height = 480 )
plot(a2,a1$Global_active_power,type = "s",xlab = " ",ylab = "Global Active Power (killowatts")
dev.off()