library(lubridate)
library(data.table)
library(dplyr)
a=fread("ExData_Plotting1/household_power_consumption.txt",na.strings = c("?"))
a1=filter(a,dmy(Date)=="2007-02-01"|dmy(Date)=="2007-02-02")
setwd("ExData_Plotting1")
a2=dmy(a1$Date)+hms(a1$Time)
a1$timedate=a2
par("mfrow"=c(2,2))
plot(a1$timedate,a1$Global_active_power,ylab = "Global Active Power",type = "s",xlab = " ")
plot(a1$timedate,a1$Voltage,ylab = "Voltage",type = "s",xlab = "datetime")
with(a1,plot(timedate,Sub_metering_1,xlab=" ",ylab="Energy sub metering",type="s"))
with(a1,lines(timedate, Sub_metering_2,col="red"))
with(a1,lines(timedate, Sub_metering_3,col="blue"))
legend("topright",col=c("black","red","blue"),lty="solid",
legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(a1$timedate,a1$Global_reactive_power,xlab = "datetime",type="s",ylab = "Global_reactive_power")
dev.copy(png, width=480, height=480, file = "plot4.png")
dev.off()